/**
 * Writes app version from package.json + git commit count.
 * Run automatically via prestart / prebuild.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const frontendRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(frontendRoot, '..');

function git(command) {
  try {
    return execSync(command, { cwd: repoRoot, encoding: 'utf8' }).trim();
  } catch {
    return null;
  }
}

const pkg = JSON.parse(readFileSync(join(frontendRoot, 'package.json'), 'utf8'));
const [major, minor] = pkg.version.split('.');
const commitCount = git('git rev-list --count HEAD');
const shortSha = git('git rev-parse --short HEAD') ?? 'unknown';

const appVersion = commitCount
  ? `${major}.${minor}.${commitCount}`
  : `${major}.${minor}.0+${shortSha}`;

const outputPath = join(frontendRoot, 'src/environments/version.generated.ts');
const contents = `// Auto-generated by scripts/generate-version.mjs — do not edit.
export const APP_VERSION = '${appVersion}';
export const APP_COMMIT = '${shortSha}';
`;

writeFileSync(outputPath, contents, 'utf8');
console.log(`App version: ${appVersion} (${shortSha})`);
